Portfolio: Setup and mobile first
AceMannie/Portfolio. pull request #1
Opened 2023-03-23 11:26 UTC by AceMannie

In this Project :

Added `README.md` file
Added `Linters.yml` file
Added `Html.index` file
Added `Stylecss` file
Added `.gitignore` file

2023-03-23 13:46 UTC, AHP15 requested changes
Hi @AceMannie , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![soclose](https://user-images.githubusercontent.com/97100091/199273222-010c4c63-4b9f-4149-9cac-ca9dde88e551.gif)


## Highlights
✅ Good GitHub Flow
✅ No linter errors
✅ great design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 13:46 UTC, AHP15 commented on index.html
> +        <img src="images/My Logo.png" alt="Mylogo">
- [ ] Kindly put this `img` tag in with the `nav` tag in a `header` because typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info

2023-03-23 13:46 UTC, AHP15 commented on style.css
> +} */
- [ ] Kindly remove this commented code because it will clutter your code

2023-03-23 16:29 UTC, AceMannie commented
Thank you for reviewing the code @Abdessittir .

Kindly review the new changes.

Thanks.

2023-03-24 07:33 UTC, levy002 requested changes
## Hello @AceMannie   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- Descriptive PR :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 07:33 UTC, levy002 commented on README.md
> +-->
- [OPTIONAL] KIndly make sure to remove all comments and instructions in order to keep your repo clean and professional.

2023-03-24 07:33 UTC, levy002 commented on index.html
> +        <img src="images/My Logo.png" alt="Mylogo">
- [OPTIONAL] Kindly make sure to wrap your logo into the Anchor `a` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-03-24 07:33 UTC, levy002 commented on index.html
> +        </u>
- [ ] As explained by the previous reviewer, the `nav` tag must be inside the `header` tag but I can see you have removed it. Please know that always the hamburger icon must be wrapped into the `nav` tag. Kindly make sure to change the `u` tag to the `nav` tag in order to follow the HTML best practices and meet the project requirements.

2023-03-24 07:33 UTC, levy002 commented on index.html
> +                </li>
- [ ] As requested by the previous reviewer, Kindly make sure to wrap all your image icons into the Anchor `a` tag. Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using the `href` attribute.

2023-03-24 08:49 UTC, AceMannie commented
@levy002  thank you for reviewing the code.

Kindly take a review at the new changes and i hope i'm good to go.

I wait for your response.

2023-03-24 08:51 UTC, levy002 commented
Hello @AceMannie, If you are ready please go ahead and submit again your PR link in the dashboard for the second review.

2023-03-24 09:12 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @AceMannie, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented previous suggestions.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-24 09:28 UTC, merged